# Generated by Django 5.1.1 on 2024-11-05 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Действует'), ('deleted', 'Удалён')], default='active', max_length=20)),
                ('image_url', models.URLField(max_length=500)),
                ('players', models.CharField(max_length=50)),
                ('tileset', models.CharField(max_length=50)),
                ('overview', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MapPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удалён'), ('submitted', 'Сформирован'), ('completed', 'Завершён'), ('rejected', 'Отклонён')], default='draft', max_length=20)),
                ('player_login', models.CharField(blank=True, max_length=150, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('submit_date', models.DateTimeField(blank=True, null=True)),
                ('complete_date', models.DateTimeField(blank=True, null=True)),
                ('popularity', models.IntegerField(blank=True, default=1, null=True)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_map_pools', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_pools', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MapMapPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmstu_lab.map')),
                ('map_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapmappool', to='bmstu_lab.mappool')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('map_pool', 'map'), name='unique_map_pool_map')],
            },
        ),
    ]
