# Generated by Django 5.1.1 on 2024-09-29 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapcart',
            name='quantity',
        ),
    ]
