# Generated by Django 5.1.1 on 2024-11-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappool',
            name='popularity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
