# Generated by Django 5.1.1 on 2024-10-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0005_authuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='is_creator',
            field=models.BooleanField(default=False, verbose_name='Is Creator'),
        ),
        migrations.AddField(
            model_name='authuser',
            name='is_moderator',
            field=models.BooleanField(default=False, verbose_name='Is Moderator'),
        ),
    ]
