# Generated by Django 5.1.1 on 2024-10-16 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0006_authuser_is_creator_authuser_is_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapmappool',
            name='map_pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapmappool', to='bmstu_lab.mappool'),
        ),
    ]
