# Generated by Django 5.1.1 on 2024-10-16 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0007_alter_mapmappool_map_pool'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='authuser',
            table='bmstu_lab_authuser',
        ),
    ]
