# Generated by Django 5.1.1 on 2024-10-16 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0009_alter_authuser_options_alter_authuser_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
